### PR TITLE
Show StatusBar on the right

### LINKED ISSUE #575: Status Bar Settings
Rewrite looks really interesting, great job guys!

Any way to disable the "Current File" / "Project" tabs? It's a little bit too much clutter for me. Perhaps it should be a setting rather than a fast toggle?

Another quick question, would you consider adding a setting to put the "No Errors" message on the right side of the sidebar again? Most other plugins use the right side, so it just looks odd to me.

Thanks for your time!

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #575

### CODE REVIEW

**Comment by steelbrain** [comment]
Ready for a review people.

**Comment by AsaAyers** [comment]
screenshot?

**Comment by steelbrain** [comment]
screenshot from 2015-06-23 09 09 28

**Comment by iam4x** [comment]
I would like to have an option to make it right / left, with left by default as our first implementation

**Comment by steelbrain** [comment]
@iam4x I'm happy to make it configurable if others agree.

**Comment by k2b6s9j** [comment]
I'm fine with it. Looks good to me. I'd also be okay with add an option to disable the tabs.

**Comment by ababol** [comment]
@iam4x Yep, I agree, it might be useful.

**Pull request closed without merging**
