### PR TITLE
Add linter-swiftc to Readme Linter List.

### PR DESCRIPTION
**Pull request by k2b6s9j**

### CODE REVIEW

**Comment by iam4x** [comment]
Hello @k2b6s9j,

Could you add more instruction on your own `README.md` before merging this.

**Comment by k2b6s9j** [comment]
I just created a proper read me for the project. Sorry about the delay. Let me point the link at the new location and this will be good to go.

**Comment by k2b6s9j** [comment]
Never mind, thought I was pointing at the repo, not the package page. Good to merge!

**Comment by iam4x** [comment]
:+1:

**Pull request merged**
