### PR TITLE
:memo: atom-typescript for TypeScript

### PR DESCRIPTION
**Pull request by basarat**

### CODE REVIEW

**Comment by hd-deman** [comment]
Looks like something more complex than just linter-package.

**Comment by basarat** [comment]
> Looks like something more complex than just linter-package.

It is much more complex, and does a lot more. Perhaps you only want to list simple linters? If so you can close this. Would also like @park9140's opinion.

**Comment by hd-deman** [comment]
why you not use [linter-tslint](https://atom.io/packages/linter-tslint) as dependency instead of implement same functionality as part of you package?

**Comment by basarat** [comment]
> why you not use linter-tslint as dependency instead of implement same functionality as part of you package

I agree. I haven't reimplemented it. The functionality provided is different. One is a *linter* (tslint) the other (this one) is a `compiler` / `syntax` / `semantic` checker :heart:

**Comment by park9140** [comment]
@basarat, @hd-deman, we should probably think about adding a list of external "build" tools that use the linter as their error output.  There are a couple of these packages now, and most of them depend on a core package to provide the underlaying 'linter' error messages, so they can't easily be separated from their core functionality.

**Pull request closed without merging**
