### PR TITLE
Fix deprication in space pen ussage

### PR DESCRIPTION
**Pull request by park9140**
@dmnd, fixes issue with space pen version rolling forward.  Also corrects a couple deprications that slipped through.

### CODE REVIEW

**Comment by wcandillon** [comment]
+1

**Comment by anazar** [comment]
+1

**Comment by park9140** [comment]
For those who run into this until it gets pulled there is a workaround.

```bash
cd ~/.atom/packages/linter
npm install space-pen@4.2.2
```

**Comment by wcandillon** [comment]
I tried this branch and it works great.

**Comment by park9140** [comment]
Went ahead and published as a patch release 0.9.1,  if anyone has any comments we can fix them later.

**Comment by sirianni** [comment]
I just updated to 0.9.1 and I'm still seeing the issue.

**Comment by park9140** [comment]
@sirianni, that is strange,  can you verify the version of space-pen you have installed after updating? 

```
cd ~/.atom/packages/linter
cat package.json
cat node_modules/space-pen/package.json
```

I assume there is something weird about npm install when apm updates your packages that doesn't listen to the version correctly when checking for updates.  

As a quick fix you can probably remove the package restart atom then reinstall.

**Comment by sirianni** [comment]
I have version `4.3.3` of space-pen
```
[esirianni@ub-esirianni ~/.atom/packages/linter]
$ head package.json 
{
  "name": "linter",
  "main": "./lib/init",
  "version": "0.9.1",
  "private": true,
  "description": "Validates your code using linters.",
  "repository": {
    "type": "git",
    "url": "https://github.com/AtomLinter/Linter.git"
  },

[esirianni@ub-esirianni ~/.atom/packages/linter]
$ grep '"space-pen":' package.json      
    "space-pen": "^4.3.3",
          "space-pen": "^4.3.3",

[esirianni@ub-esirianni ~/.atom/packages/linter]
$ head node_modules/space-pen/package.json 
{
  "name": "space-pen",
  "version": "4.3.3",
  "description": "Write markup on the final frontier",
  "main": "./lib/space-pen.js",
  "scripts": {
    "prepublish": "grunt prepublish",
    "test": "grunt test",
    "start": "grunt start"
  },
```

**Comment by dmnd** [comment]
Thanks for taking the initiative here @park9140, I'll take a look now

**Comment by dmnd** [comment]
This pull looks ok to me but I am ignorant of the changes in space-pen that necessitate it. 

[It looks like we should upgrade](https://github.com/atom/atom/commit/d90c8c0fb71d341f45fff0de2e9fed61b79390e8) all the way to 5 if we can?

**Comment by park9140** [comment]
@dmnd, definitely I tried though and got some wierd results going to 5 so I did the short change of going to the latest 4

**Comment by park9140** [comment]
@sirianni, can you post the error you are getting if you are still getting it after restarting atom?

**Comment by sirianni** [comment]
@park9140 I don't have it anymore, but I believe it was the same as the original error: `Failed to activate package named 'linter' Error: The ::beforeRemove hook has been replaced by ::detached.`

Your suggestion of removing the linter package and reinstalling it worked for me.

**Pull request merged**
