### PR TITLE
Ignore lint requests until file is saved somewhere

### PR DESCRIPTION
**Pull request by steelbrain**
/cc @AsaAyers

### CODE REVIEW

**Comment by AsaAyers** [comment]
Would you mind updating the changelog from the PR so we don't forget? Maybe we should just keep a `# upcoming` section at the top and we'll replace it with the version when it releases?

**Comment by steelbrain** [comment]
Sounds great.

**Comment by steelbrain** [comment]
Done.

**Comment by steelbrain** [comment]
Merging based on the discussion.

**Pull request merged**
