### PR TITLE
Add linter-stylus to readme

### PR DESCRIPTION
**Pull request by olmokramer**

### CODE REVIEW

**Comment by iam4x** [comment]
:+1:

**Comment by olmokramer** [comment]
I'm sorry, I completely forgot about this package, but there's [linter-stylint](https://atom.io/packages/linter-stylint) now that's better than linter-stylus, so I no longer support linter-stylus. I think you should add that one to the list.

**Comment by olmokramer** [comment]
I see linter-stylint is already in the list.

**Comment by iam4x** [comment]
Alright!

**Pull request closed without merging**
