### PR TITLE
change 'current file' text to just 'file'

### PR DESCRIPTION
**Pull request by devoncarew**
Change the `Current File` tab title to just `File`. This matches the `Project` tab a bit better, and is more terse - status bar space is at a premium :)

### CODE REVIEW

**Comment by devoncarew** [comment]
screen shot 2015-06-26 at 11 03 27 am

**Comment by k2b6s9j** [comment]
:+1:

**Comment by steelbrain** [comment]
A changelog entry please?

**Comment by devoncarew** [comment]
> A changelog entry please?

Added

**Comment by steelbrain** [comment]
LGTM. Thanks :rose:

**Pull request merged**
