### PR TITLE
Status bar summary

### PR DESCRIPTION
**Pull request by ababol**
screen shot 2014-12-03 at 21 46 54

So it display the number of errors/warning.

Let me know if you need further information about the commit.

See: https://github.com/AtomLinter/Linter/issues/242

### CODE REVIEW

**Comment by ababol** [comment]
Hey @dmnd! Happy new year!

Do you plan to merge this soon? :smile: 

68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3135333034352f32343930312f62396535363132302d346163342d313165322d393035612d3833353061643532613965342e6a706567

**Comment by jonathandelgado** [comment]
+1 on this, great work @ababol

**Comment by dmnd** [comment]
Sorry I took so long on this, I've been spending time on other projects. But I wish I tried this earlier, it's really useful! Merging.

**Comment by dmnd** [comment]
I'll publish a release later tonight after attempting to fix some bugs that have cropped up.

**Pull request merged**
