### PR TITLE
Add TravisCI config and a spec

### PR DESCRIPTION
**Pull request by AsaAyers**

### CODE REVIEW

**Comment by steelbrain** [comment]
Does it actually pass those specs? You are missing a lot of properties there :sweat_smile:

**Comment by AsaAyers** [comment]
Yes, you can see the specs I wrote are only concerned with that one property. We should expand it and write specs for each aspect of LegacyAdapter's behavior

**Comment by AsaAyers** [comment]
IMO having one giant spec that tests every aspect of legacyAdapter is not a good idea

**Comment by steelbrain** [comment]
In that case LGTM.

**Pull request merged**
