### PR TITLE
Spec out the Helpers.

### PR DESCRIPTION
**Pull request by k2b6s9j**
In preparation of the expansion of the Helpers for CLIs I've started creating specs for the existing Helpers.

### CODE REVIEW

**Comment by steelbrain** [comment]
Do they pass?

**Comment by k2b6s9j** [comment]
[Yes. Yes they do.](https://travis-ci.org/AtomLinter/Linter/builds/69087655)

**Comment by steelbrain** [comment]
LGTM

**Comment by k2b6s9j** [comment]
You should merge if it looks good. Or if you want a second opinion, you could wait.

**Comment by steelbrain** [comment]
I think we might have an uncaught error here https://travis-ci.org/AtomLinter/Linter/builds/69087655#L100

**Comment by steelbrain** [comment]
or maybe it's just the notification's CLI info.

**Comment by k2b6s9j** [comment]
You log directly to console before throwing. https://github.com/AtomLinter/Linter/blob/master/lib/helpers.coffee#L17-L18

**Comment by steelbrain** [comment]
Fair enough

**Pull request merged**
