### PR TITLE
Fixed bug where defaultLevel is not used properly

### PR DESCRIPTION
**Pull request by code-tree**

### CODE REVIEW

**Comment by k2b6s9j** [comment]
:+1:

**Comment by steelbrain** [comment]
@k2b6s9j is `@defaultLevel` **always** defined?

**Comment by k2b6s9j** [comment]
@steelbrain By default it is defined as 'error'. See: https://github.com/AtomLinter/Linter/blob/master/lib/linter.coffee#L40

**Comment by steelbrain** [comment]
LGTM.

**Pull request merged**
