### PR TITLE
Add JSONiq and XQuery support

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by dmnd** [comment]
Hmm, usually the grammar package is separate from the linter implementation. All linters live in the AtomLinter org - do you mind splitting things up?

**Comment by wcandillon** [comment]
@dmnd I'd like to split things up when it's possiblr to install plugin dependency automatically. Right you need to install two plugins. You would need to install 3. What do you think?


Awesome job btw!

**Comment by park9140** [comment]
@wcandillon, I am hoping to roll to a new api for linters in #387,  one of the things that has been discussed about the services api is that it may start being used as plugin dependency management.  Hopefully this will happen soon :fingers crossed:

**Comment by wcandillon** [comment]
@park9140 super fancy :)

**Comment by iam4x** [comment]
Since it's just a link, I'm good with it. Still pending since 5feb, I merge it :)

**Pull request merged**
