### PR TITLE
Add disallowed types config

### LINKED ISSUE #692: Option to hide warnings and display errors only
Hi, is there an option to toggle the display of warnings, so we can ignore them if needed? Some SCSS files I have report warnings on nearly every line but it's otherwise compiling fine and meets my standards. It just adds quite a lot of visual clutter for many lines.

screenshot_114

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #692

### CODE REVIEW

**Comment by iam4x** [comment]
Nicely done @steelbrain, looks good to me :+1:

**Comment by steelbrain** [comment]
:cocktail: Cheers

**Comment by iam4x** [comment]
I'll keep my french tradition :wine_glass:

**Comment by drawcard** [comment]
Thank you!

**Comment by drawcard** [comment]
I will celebrate with an Aussie tradition :beers: ;)

**Pull request merged**
